language: go
sudo: false

cache:
  directories:
  - vendor/bundle

go:
  - tip

before_install:
  - rvm install ruby --latest
  - bundle install --path vendor/bundle --jobs 3
  - bundle exec jekyll build
  - cd _site/

script:
  - go test

